export { Footer } from './Footer/Footer';
export { Header } from './Header/Header';
export { GameItem } from './GameItem/GameItem';
export { WinLoseBoard } from './WinLoseBoard/WinLoseBoard';
export { Modal } from './Modal/Modal';
export { FailWithdrawalModal } from './FailWithdrawalModal/FailWithdrawalModal';
export { WithdrawalModal } from './WithdrawalModal/WithdrawalModal';

export { Avatar } from './UI/Avatar/Avatar';
export { Circle } from './UI/Circle/Circle';
export { UserSlider } from './UI/UserSlider/UserSlider';
export { RoundButton } from './UI/RoundButton/RoundButton';
export { LastBetsSlider } from './UI/LastBetsSlider/LastBetsSlider';
export { SecondaryButton } from './UI/SecondaryButton/SecondaryButton';
export { BalanceButton } from './UI/BalanceButton/BalanceButton';
export { HeaderSection } from './UI/HeaderSection/HeaderSection';
export { SuccessSection } from './UI/SuccessSection/SuccessSection';
export { ModalMainButton } from './UI/ModalMainButton/ModalMainButton';
export { BalanceActionButton } from './UI/BalanceActionButton/BalanceActionButton';
